name: Java CI with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up the JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          cache: 'maven'
      - name: Configure Problem Matchers
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
          echo "::remove-matcher owner=java::"
      - name: Get Galaxy access token
        run: |
          opts=(
            -fL
            -H 'Authorization: Basic ${{ secrets.GALAXY_CLIENT_SECRET }}'
            -H 'Content-Type: application/x-www-form-urlencoded'
          )
          token=$(curl "${opts[@]}" "${{ vars.GALAXY_BASE_URI }}/oauth/v2/token?token_format=oauth2" -d grant_type=client_credentials | jq -er '.access_token')
          echo "OPENAPI_BEARER_TOKEN=$token" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn -B package
        env:
          GALAXY_BASE_URI: ${{ vars.GALAXY_BASE_URI }}
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test report ${{ github.job }}
          path: |
            **/surefire-reports/TEST-*.xml
          retention-days: 5
