name: Release with Maven

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up the JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          cache: 'maven'

      - name: Configure Problem Matchers
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
          echo "::remove-matcher owner=java::"

      - name: Configure Git user
        run: |
          git config user.name "automation-starburstdata"
          git config user.email "automation@starburstdata.com"

      - name: Prepare release
        run: ./mvnw -B release:prepare
        env:
          OPENAPI_CLIENT_ID: ${{ secrets.OPENAPI_CLIENT_ID }}
          OPENAPI_CLIENT_SECRET: ${{ secrets.OPENAPI_CLIENT_SECRET }}

      - name: Save version number in env
        run: |
          echo "VERSION=$(grep 'project.rel.*=' release.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Publish JAR
        run: ./mvnw -B release:perform -Darguments=-Dgpg.skip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ env.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          setup-java: false

      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test report ${{ github.job }}
          path: |
            release.properties
            **/surefire-reports/TEST-*.xml
            out/jreleaser/trace.log
            out/jreleaser/output.properties
          retention-days: 5
